[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :99 -screen 0 500x600x24
autorestart=true

[program:x11vnc]
command=x11vnc -display :99 -forever -shared -rfbport 5900 -nopw
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc/ 6080 localhost:5900
autorestart=true

[program:app]
command=python /app/app.py
environment=DISPLAY=":99"
autorestart=true